"""empty message

Revision ID: 09f5121cb943
Revises: 
Create Date: 2023-04-16 12:20:11.550819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f5121cb943'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('customerID', sa.Integer(), nullable=False),
    sa.Column('fullName', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phoneNumber', sa.Integer(), nullable=False),
    sa.Column('adress', sa.String(length=30), nullable=False),
    sa.Column('postalCode', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('customerID')
    )
    op.create_table('hotelroom',
    sa.Column('roomID', sa.Integer(), nullable=False),
    sa.Column('roomNumber', sa.Integer(), nullable=False),
    sa.Column('roomType', sa.String(length=10), nullable=False),
    sa.Column('extraBedAvailability', sa.Integer(), nullable=False),
    sa.Column('maxPersonsInRoom', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('roomID')
    )
    op.create_table('invoice',
    sa.Column('fakturaID', sa.Integer(), nullable=False),
    sa.Column('customer_ID', sa.Integer(), nullable=False),
    sa.Column('startDate', sa.Date(), nullable=False),
    sa.Column('endDate', sa.Date(), nullable=False),
    sa.Column('invoicePaid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_ID'], ['customer.customerID'], ),
    sa.PrimaryKeyConstraint('fakturaID')
    )
    op.create_table('reservation',
    sa.Column('reservationID', sa.Integer(), nullable=False),
    sa.Column('customer_ID', sa.Integer(), nullable=False),
    sa.Column('room_ID', sa.Integer(), nullable=False),
    sa.Column('extraBed', sa.Boolean(), nullable=False),
    sa.Column('extraBedOneOrTwo', sa.Integer(), nullable=False),
    sa.Column('arrivalDate', sa.Date(), nullable=False),
    sa.Column('departureDate', sa.Date(), nullable=False),
    sa.Column('bookDate', sa.Date(), nullable=False),
    sa.Column('faktura_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_ID'], ['customer.customerID'], ),
    sa.ForeignKeyConstraint(['faktura_ID'], ['invoice.fakturaID'], ),
    sa.ForeignKeyConstraint(['room_ID'], ['hotelroom.roomID'], ),
    sa.PrimaryKeyConstraint('reservationID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('invoice')
    op.drop_table('hotelroom')
    op.drop_table('customer')
    # ### end Alembic commands ###
