"""Initial migration.

Revision ID: 54dfbadd990a
Revises: 
Create Date: 2022-12-10 09:58:51.673321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54dfbadd990a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faktura_ID', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'invoice', ['faktura_ID'], ['fakturaID'])
        batch_op.drop_column('fakturaID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fakturaID', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('faktura_ID')

    # ### end Alembic commands ###
